# Generated by Django 6.0.3 on 2026-03-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendiente',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
