# Generated by Django 6.0.3 on 2026-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_cliente_mascota_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='dueno',
            field=models.CharField(default='Sin dueño', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='mascota',
            field=models.CharField(max_length=100),
        ),
    ]
