# Generated by Django 6.0.3 on 2026-03-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_cita_dueno_alter_cita_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='dueno',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
