# Generated by Django 6.0.3 on 2026-03-19 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_cita_dueno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='dueno',
        ),
        migrations.AlterField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota'),
        ),
    ]
