# Generated by Django 6.0.3 on 2026-03-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_remove_cita_dueno_alter_cita_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='dueño',
            new_name='dueno',
        ),
    ]
